restserver:
  addr : ":8080"
  pprofenable: 1

fileserver:
  inputpath: "./input.txt"
  outputpath: "./output.txt"

loggerconfig:
  appname : "checkout-case"
  loglevel : 0
  logencoding : "console"
  environmenttype : "production"
  graylogaddr : ""

mongodb:
  addr: "localhost"
  port: 27017
  user: "root"
  password: "example"
  timeout: 5000
  name: "shopping"
  collection: "carts"